defaults:
  - _self_
  # 1. Change env to 'conformer' (we will create this config file below)
  - env: conformer
  - gflownet: flowmatch
  # 2. Change policy to a custom config, or override 'mlp' below
  - policy: heterogeneous
  # 3. Change proxy to use the MMFF energy
  - proxy: molecule
  - logger: wandb
  - user: julkuhn

# Device
device: cuda
float_precision: 32
n_samples: 100
seed: 0

hydra:
  run:
    dir: ${user.logdir.root}/${now:%Y-%m-%d_%H-%M-%S}
  #sweep:
    #dir: ${user.logdir.root}/multirun/${now:%Y-%m-%d_%H-%M-%S}
  #job:
    # See: https://hydra.cc/docs/upgrades/1.1_to_1.2/changes_to_job_working_dir/
    # See: https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/#disable-changing-current-working-dir-to-jobs-output-dir
    #chdir: True